FROM node:alpine as builder
WORKDIR /app
ADD package*.json ./
RUN yarn install
ADD . .
RUN yarn run build --prod

FROM node:alpine
WORKDIR /app
COPY --from=builder /app/dist/ ./dist
ADD package.json ./
RUN yarn install --omit=dev
CMD ["node","./dist/main.js"]