name: Check
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: lint tekshirish
        run: yarn lint
  test:
    needs: [lint]
    strategy:
      matrix:
        version: [18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.version}}
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Test tekshirish
        env:
          PORT: ${{secrets.PORT}}
        run: yarn run test