name: Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint tekshirish
        run: npm run lint

  test:
    needs: [lint]
    strategy:
      matrix:
        version: [18, 20]  # 12 ni olib tashlash tavsiya qilinadi, EOL bo‘lgani uchun
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Test tekshirish
        env:
          PORT: ${{ secrets.PORT }}
        run: npm test
